# Generated by Django 5.0.4 on 2024-05-06 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='imagen/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Categoria de productos',
                'verbose_name_plural': 'Categorias de productos',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='imagen/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Residuo',
                'verbose_name_plural': 'Residuos',
                'db_table': 'Residuo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion_breve', models.CharField(max_length=100, verbose_name='Descripción breve')),
                ('descripcion_extendida', models.CharField(max_length=500, verbose_name='Descripción extendida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('imagen_principal', models.ImageField(upload_to='imagen/', verbose_name='Imagen principal')),
                ('imagen_secundaria_1', models.ImageField(blank=True, null=True, upload_to='imagen/', verbose_name='Imagen secundaria 1')),
                ('imagen_secundaria_2', models.ImageField(blank=True, null=True, upload_to='imagen/', verbose_name='Imagen secundaria 2')),
                ('imagen_secundaria_3', models.ImageField(blank=True, null=True, upload_to='imagen/', verbose_name='Imagen secundaria 3')),
                ('imagen_360', models.ImageField(blank=True, null=True, upload_to='imagen/', verbose_name='Imagen 360')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
                ('residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.residuo', verbose_name='Tipo de residuo que puede contener')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'db_table': 'Contenedor',
            },
        ),
    ]
