# Generated by Django 5.0.4 on 2024-05-06 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('inventario', '0001_initial'),
        ('reparto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Monto total')),
                ('fechahora_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora_orden', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de registro del orden')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reparto.entrega', verbose_name='Entrega')),
                ('estado_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.estadoorden', verbose_name='Estado de la orden')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'Orden',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.orden', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Detalle orden',
                'verbose_name_plural': 'Detalles orden',
                'db_table': 'DetalleOrden',
            },
        ),
    ]
