# Generated by Django 5.0.4 on 2024-05-06 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellido_p', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido paterno')),
                ('apellido_m', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido materno')),
                ('numero_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de documento')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.tipodocumento', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
