# Generated by Django 5.0.4 on 2024-05-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
    ]
